### ISSUE TITLE
请问customUrl该如何设置？

### ISSUE THREAD

**Issue by hzfmer** [PicGo/vs-picgo#10]
似乎默认图片保留原有名字，我想请问除此之外可以加上别的内容吗？ 比如`${mdFileName}` ，`${fileName}` 以及 `${date}`。
我把 `customUrl` 设置成 `${fileName}_${dateTime}` 之类就失败了。

希望能给一个关于这个的教程， 非常感谢！

**Comment by Spades-S** [comment]
@hzfmer 详细的配置可以参见[PicGo文档](https://picgo.github.io/PicGo-Doc/zh/guide/config.html#%E5%9B%BE%E5%BA%8A%E5%8C%BA)

**Comment by hzfmer** [comment]
不好意思，我在这个文档里只看到关于桌面版本的设置，内容包括
> PicGo预置的有四种链接格式：Markdown\HTML\URL\UBB。如果你都不喜欢，想要自定义链接格式，可以选择Custom，然后在PicGo设置里点击自定义链接格式，然后你可以配置自己想要的复制的链接格式。

> 开启之后会自动将上传的文件名替换成时间戳： ![](https://user-images.githubusercontent.com/12621342/40976264-2de18afe-6900-11e8-8f35-746820632eb8.png）

这些都不适用于 vscode 插件版。 而且不知道为什么我没法运行桌面版，所以桌面端设置完的 `config` 长什么样都不知道。。。

**Comment by Spades-S** [comment]
@hzfmer vscode插件目前支持自定义图片名上传，上传前选中文字即可，需要更新到1.0.5，修了一个小bug。路径可以通过配置文件配置，具体配置在picgo里。链接格式目前是只支持markdown的
![image](https://user-images.githubusercontent.com/18718461/53321283-f2f75200-3912-11e9-86fb-283660e27932.png)
![image](https://user-images.githubusercontent.com/18718461/53321311-060a2200-3913-11e9-85ac-47990c0e780c.png)

**Comment by Spades-S** [comment]
可以把你预想的功能描述下，后面我尽量去实现

hzfmer <notifications@github.com> 于2019年2月25日周一 下午3:20写道：

**Comment by hzfmer** [comment]
谢谢！
我的想法是能够提供一些变量用来给图片重命名 (vs_picgo)，比如 `mdFileName` （markdown 文件名）， `FileName` （图片文件名），`date` （插入时间）。 这样更好整理，也便于以后查找。

可以参考另一个七牛图床的[插件](https://github.com/favers/vscode-qiniu-upload-image)。
> 参数化命名，暂时支持 ${fileName}、${mdFileName}、${date}、${dateTime}

**Comment by Molunerfinn** [comment]
@Spades-S 如果有空可以参考 [picgo-plugin-autocopy](https://github.com/PicGo/picgo-plugin-autocopy)的实现

**Comment by Spades-S** [comment]
@Molunerfinn 好

**Comment by upupming** [comment]
A reasonable feature, I will try to implement it~
@Molunerfinn This page https://picgo.github.io/PicGo-Core-Doc/zh/guide/config.html#picbed doesn't mention what the `customUrl` does for `picgo-core`. Is this useless? If yes, we should delete this configuration because it is misleading.

**Comment by Molunerfinn** [comment]
@upupming 桌面版在上传图片后会复制链接，复制链接有5种格式：
![image](https://user-images.githubusercontent.com/12621342/55325163-cbb61680-54b6-11e9-99a8-38311d1807a1.png)
最后一种是 `Custom`，可以让用户自定义复制的链接的模板。

但是 `PicGo-Core` 本身是不带有上传图片成功后自动复制到剪贴板的功能的。所以 `PicGo-Core` 本身没是没有 `Custom` 的配置。

至于阿里云、腾讯云等的 `customUrl` 只是用来自定义自己的域名而已。比如阿里云上传图片后系统会自动分配的地址比如是`https://xxx.aliyun.com/xxx.jpg` 。如果想使用自己的域名才要设置 `customUrl`，比如设置成 `https://piegg.cn`，那么上传成功后的图片地址就是 `https://piegg.cn/xxx.jpg`。

![image](https://user-images.githubusercontent.com/12621342/55325424-a2e25100-54b7-11e9-9c3e-c9f8d25b9bfd.png)

而vs-picgo本身是一个用于markdown的插件，所以它的上传成功后的链接格式理论上应该是使用markdown的格式的。所以楼主这里所说的 `customUrl` 实际上跟阿里云、腾讯云配置里的 `customUrl` 并不是同一个东西。而是更像桌面端的 `pasteStyle.custom` 的配置。

而vs-picgo的 `customUrl` 实际上可以类似  [picgo-plugin-autocopy](https://github.com/PicGo/picgo-plugin-autocopy) 里的实现，实现一个可以让用户自定义模板的配置。至于是不是只有 `$url` 作为模板变量，就不一定了，也可以加入一些方便的模板变量，比如 `$fileName` 、`$date` 等。这个就看作者或者你如果要贡献代码时怎么考虑了。

**Comment by upupming** [comment]
@Molunerfinn 感谢及时指点！我会先阅读一下 picgo-plugin-autocopy ，再做贡献。

另外还有一个问题：

可以在 `PicGo-Core` 或者 `PicGo` 的文档中说明 `customUrl ` 只对部分图床自定义域名有用。现在文档是直接指向了 `PicGo` 的文档，但是在 `PicGo` 的文档中并没有找到  `customUrl ` 的相关说明。对于没有安装 `PicGo` 查看不到 `data.json` 的用户就不太清楚各个配置项的键值。可以提供一个模板文件并且做相应的说明。

**Comment by Molunerfinn** [comment]
回头我会把配置的键值的名称补到配置后面。可能顺便给个截图更直观点。
