### ISSUE TITLE
打包可能出现了问题，WSL被识别成了pure linux

### ISSUE THREAD

**Issue by JeffersonQin** [PicGo/vs-picgo#100]
- vs-picgo: 2.1.3
- VSCode Version: 1.57.1 (system setup)
- Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
- Date: 2021-06-17T13:28:07.755Z
- Electron: 12.0.7
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.19042

`PicGo`的最新版(2.1.3)，在`WSL`下调用剪切板时被识别成`linux`，因为出现了`Please install xclip before run picgo`的提醒。

拉取了代码，在本地对于`WSL`剪切板功能进行**直接测试**：
- 在`WSL`环境内启动`VSCode`调试，上传成功
- 在`Windows`环境内启动`VSCode`调试，再进入`WSL`插件，上传成功
- 对代码进行手动打包，打包命令：`vsce package`，上传成功

怀疑是打包过程中出了问题。

**Comment by upupming** [comment]
@JeffersonQin 使用最新版的 2.1.3，你可以直接进行调试的，直接修改现有代码 `~/.vscode/extensions/spades.vs-picgo-2.1.3/dist/extension.js`，在里面加 log 就行了，你看看有没有什么问题

代码被 minifiy 了，你可以先用 prettier 格式化一下

**Comment by upupming** [comment]
我看 wsl.sh 并没有被打包：
![image](https://user-images.githubusercontent.com/24741764/130271478-0f9376c9-6fe0-4580-95b6-053886099c54.png)

我周末处理一下

**Comment by upupming** [comment]
我看 GitHub 上的 Release 是对的：
![image](https://user-images.githubusercontent.com/24741764/130271949-a9aa22e6-bd36-4662-bb40-071918c85e78.png)
你下下来看看有没有问题呢，没问题的话之后重发一下

**Comment by JeffersonQin** [comment]
就是挺奇怪的 无论是把代码clone下来本地测试 还是自己打包都ok 但是从market place安装的2.1.3却有问题🤣

**Comment by JeffersonQin** [comment]
啊 对了 今天下午我又更新了一下wsl的shell脚本，已经merge进core的主线了，这次打包如果那边release了的话可以update一下（辛苦了

**Comment by frank-mupt** [comment]
@upupming @JeffersonQin  应该是我 git pull 之后没有更新 node_modules 直接 vsce  publish 就发掉了 😰 ，我加个 publish npm scripts 吧

**Comment by JeffersonQin** [comment]
> @upupming @JeffersonQin 应该是我 git pull 之后没有更新 node_modules 直接 vsce publish 就发掉了 😰 ，我加个 publish npm scripts 吧

对，那应该就是这个问题了。一个是Core的依赖升级，还增加了`is-wsl`的新依赖（麻烦您了

**Comment by upupming** [comment]
好像没有自动更新依赖的脚本

**Comment by upupming** [comment]
@Spades-S 先不着急发包，我提几个 PR

**Comment by upupming** [comment]
应该已经没问题了
