### ISSUE TITLE
github的私有库图片的保存的token与vscode生成的不一致

### ISSUE THREAD

**Issue by inaryart** [PicGo/vs-picgo#109]
### Describe the bug
vscode上传图片到私有库时vscode生成的**图片token**与存储库的**图片token**不一致（图片已上传

这是**私有库的token**权限
![image](https://user-images.githubusercontent.com/51652878/140640761-dadc4525-2902-44e2-a7d1-6971a4ed03e0.png)

### To Reproduce

1. vscode上传图片 生成
```
https://raw.githubusercontent.com/用户/images/main/2021/时间1112.png?token=AD7XRJWL4M4EXAU
```
单机打开此链接显示
![image](https://user-images.githubusercontent.com/51652878/140640829-d3683826-004d-42e9-ba86-ec3a1d59f024.png)

2. 在私有存储库打开图片，它的链接为
```
https://raw.githubusercontent.com/用户/images/main/2021/时间1112.png?token=AD7XRJ不一致token
```

### Expected behavior

图片token一致

**Comment by upupming** [comment]
@inaryart 这个是 GitHub 自己决定的，试了一下，返回的访问用的 token 确实和你传入的 token 不一样，而且手动将输出的 token 改为你的 personal access token 反倒会 404。这个不是 vs-picgo 的问题，应该是 github 自己的安全机制啊

搜索了 GitHub 社区，官方给的反馈也是，本来就是针对每一个文件生成一个 token 的。参考 https://github.community/t/how-to-get-a-permanent-token-of-a-single-raw-file-of-a-private-github-repo-that-will-lasts-for-several-days/125205

**Comment by upupming** [comment]
@inaryart token 不一致对你使用来说会产生什么问题吗？如果没问题就没事的。
