### ISSUE TITLE
PicGo: 上传失败! 服务端出错，请重试.

### ISSUE THREAD

**Issue by codesensi** [PicGo/vs-picgo#113]
我的配置文件时这样的
![image](https://user-images.githubusercontent.com/66196408/149649876-36492c96-585b-4fe4-9ef7-78f3403f3a61.png)
我确保token是没问题的，但是上传图片时就会提示服务端出错
请问是什么原因造成的呢

**Comment by jimmy66886** [comment]
请问如何解决的呢？我也是配置的github，之前用着都没问题，今天突然就上传失败，提示服务端出错

**Comment by Liu-Jincan** [comment]
> 我的配置文件时这样的 ![image](https://user-images.githubusercontent.com/66196408/149649876-36492c96-585b-4fe4-9ef7-78f3403f3a61.png) 我确保token是没问题的，但是上传图片时就会提示服务端出错 请问是什么原因造成的呢

您好，请问您解决这个问题了吗？

**Comment by SWHL** [comment]
这个多半是因为上传的图像名字重复导致的。
