### ISSUE TITLE
[Question] how to check the log of picgo extension?

### ISSUE THREAD

**Issue by Rullec** [PicGo/vs-picgo#121]
### Describe the bug

At this moment, my vscode picgo extension doesn't work. When I hit the upload key, it just show "PicGo: image uploading... " and do nothing.

So I want to check the log to see what happened. Please tell me how to check the log of vscode picgo extension.
### To Reproduce
Just hit the key.
### Expected behavior
Image should upload.
### System information
MacOS 
### VSCode information

vscode version 1.54.1 
picgo version 2.1.0 
"picgo.configPath": "/Users/xxx/Library/Application Support/picgo/data.json",
"picgo.dataPath": "/Users/xxx/Library/Application Support/picgo/data.json",

**Comment by upupming** [comment]
@Rullec Please see the issue template, `Help` -> `Toggle Developer tools`
