### ISSUE TITLE
Save uploaded image to some log file for future backup

### ISSUE THREAD

**Issue by upupming** [PicGo/vs-picgo#13]
I think we can save all uploaded images to a file, such as `json` or `xml`. In this way, we can back up the pictures or import saved pictures to a database such as MySQL.

Any plan to add this feature? Thanks!

**Comment by Spades-S** [comment]
@upupming  Great idea! This may be the resolution to [#8](https://github.com/Spades-S/vs-picgo/issues/8). BUT, these days, I may not have time to do this. THIS WILL BE IN THE PLAN. At the same time, a pull request is always  WELCOME!

**Comment by upupming** [comment]
Cool, I will try to open a PR 😜
