### ISSUE TITLE
[Feature]: Gitlab 上传支持

### ISSUE THREAD

**Issue by HimekoEx** [PicGo/vs-picgo#134]
### 系统信息 | System Information

All

### 功能请求 | Feature request

请问能支持 `Gitlab` 的上传吗?

主要是能自己私有化部署服务器, 也能在内网用
也能直接使用官方的仓库

**Comment by Molunerfinn** [comment]
后续会想办法支持picgo插件。

**Comment by Molunerfinn** [comment]
目前你可以通过 picgo-core 或者 picgo 应用程序安装 gitlab 的picgo插件使用。

vs-picgo不会直接支持单独某种图床，但是会想办法支持 picgo 的插件生态，在 vs-picgo 中也能使用 picgo 的插件。

参考 #128
