### ISSUE TITLE
一直显示再上传中

### ISSUE THREAD

**Issue by qingfengbaili** [PicGo/vs-picgo#18]
![image](https://user-images.githubusercontent.com/44765369/55632473-f96bca00-57ec-11e9-9a84-f8206654a0c0.png)
![image](https://user-images.githubusercontent.com/44765369/55632509-0a1c4000-57ed-11e9-93d3-68807a3ae125.png)
密码被我删掉了，我不确定是什么问题，所以来问问大佬，我也找不到日志在哪里看。
vscode是最新版的。

**Comment by upupming** [comment]
2.0 版本有了精准的报错信息，请更新最新版使用~

**Comment by Molunerfinn** [comment]
@qingfengbaili 新版本可以直接在VSCode的配置界面搜索 `picgo` 来找到对应的图床配置区：
![image](https://user-images.githubusercontent.com/12621342/55768220-8ee9b100-5aae-11e9-84bb-c904fecffa30.png)
配置完图床记得把 `current` 选成你当前配置的图床比如你的是 `upyun`

**Comment by upupming** [comment]
Closed as no response, please feel free to open a new issue if the problem still exists
