### ISSUE TITLE
Setting description missing

### ISSUE THREAD

**Issue by upupming** [PicGo/vs-picgo#19]
![image](https://user-images.githubusercontent.com/24741764/55662739-f0a8e180-5848-11e9-85b3-197a04505737.png)

We should give user suggestion which settings are available and give them a description of each setting.

**Comment by upupming** [comment]
1. We should also prevent the PicGo-Core from modifying this data.json file:

![image](https://user-images.githubusercontent.com/24741764/55663769-64e98200-5855-11e9-8f34-503c6fcdb9e8.png)

**Comment by upupming** [comment]
Now I have added `configPath` and `logPath`:
![image](https://user-images.githubusercontent.com/24741764/55664115-b4cb4780-585b-11e9-8fde-6c75c9a2a4eb.png)

Still working on `picBed`...

**Comment by Spades-S** [comment]
@upupming  This way does work!  VSC can get value from  the property which looks  like `picgo.config` in usersetting.json.  The only thing we should pay attention to is these changes should be compatible.
![image](https://user-images.githubusercontent.com/18718461/55664197-2952b600-585d-11e9-8192-8feeff6becb0.png)
