### ISSUE TITLE
v2.0.1 README format at vscode market

### ISSUE THREAD

**Issue by upupming** [PicGo/vs-picgo#26]
https://marketplace.visualstudio.com/items?itemName=Spades.vs-picgo&ssr=true#overview

![image](https://user-images.githubusercontent.com/24741764/55683936-1385e380-5978-11e9-8430-9cada69e168d.png)

README format needs to be fixed.

**Comment by upupming** [comment]
Another suggestion:
![image](https://user-images.githubusercontent.com/24741764/55684296-2ac6d000-597c-11e9-9696-6af3348bdc30.png)

Change the description of this plugin so people can search with some keywords like `picture` or `upload` and catch `PicGo`.

Currently, I have to search `PicGo`, people don't know `picgo` can never know this extension:

![image](https://user-images.githubusercontent.com/24741764/55684314-5944ab00-597c-11e9-9beb-ce86c65e9937.png)

**Comment by Spades-S** [comment]
@upupming  Yeah, we should rename it to let more people catch it. How about `PicGo image uploader`.  
And, i'll do something to fix the `README` format

**Comment by Spades-S** [comment]
@upupming  Maybe, we can just attach some keywords.

**Comment by upupming** [comment]
How about this:


> A fast and powerful image upload plugin for VSCode based on PicGo. 
> Supports major picture formats and many image hosting services!

**Comment by Spades-S** [comment]
It is a good description. And keywords  in  package.json also help, how
about [image,  uploader, paste]

Li Yiming <notifications@github.com>于2019年4月7日 周日下午10:08写道：

**Comment by Spades-S** [comment]
I would like to keep the name "PicGo"😂

Li Yiming <notifications@github.com>于2019年4月7日 周日下午10:08写道：

**Comment by upupming** [comment]
"PicGo" is quite meaningful now, we know what we are talking about, but users may not.

**Comment by Spades-S** [comment]
A good description and some good keywords can let users know what it is.

Li Yiming <notifications@github.com>于2019年4月7日 周日下午10:17写道：

**Comment by Molunerfinn** [comment]
keywords are very important:
https://code.visualstudio.com/api/references/extension-manifest
![image](https://user-images.githubusercontent.com/12621342/55719484-f06b3a80-5a30-11e9-9c89-d86806e3c125.png)
I suggest using words such as `image`, `picture`, `upload`, `image upload`, `picture upload`, `markdown` etc.

**Comment by Molunerfinn** [comment]
BTW, the screenshots in README are too big for users to load. We need to compress them 😃
