### ISSUE TITLE
腾讯云上传图片名称异常

### ISSUE THREAD

**Issue by chhpt** [PicGo/vs-picgo#37]
上传的图片名称中出现了 undefined，原图片名称 cli-init.jpg，命名规则：

```
${fileName}-${date}${extName}
```
结果
undefinedcli-init-2019-4-24.jpg

**Comment by upupming** [comment]
你 `customOutputFormat` 是怎么设置的？
是从剪切板还是文件浏览器上传的？

**Comment by chhpt** [comment]
@upupming 从输入框，输入绝对路径

**Comment by chhpt** [comment]
@upupming GIF

![2019-04-24 17 12 42](https://user-images.githubusercontent.com/19288423/56647591-50f6aa80-66b4-11e9-858a-d3aa3910f730.gif)

**Comment by upupming** [comment]
复现成功，感谢反馈！

**Comment by upupming** [comment]
已在 dev 中修复，请下载 [vs-picgo 开发版](https://dev.azure.com/PicGo/vs-picgo/_build/results?buildId=27)。

**Comment by xiehongxin** [comment]
![image](https://user-images.githubusercontent.com/23290328/73594227-5f2cfd80-4547-11ea-8fc9-57f1b9d2dcf4.png)

@upupming 好像打包失败了，没办法下载

**Comment by upupming** [comment]
@xiehongxin 已经更换 CI 为 GitHub Actions，可在这里下载最新版：https://github.com/PicGo/vs-picgo/actions/runs/33889307 ，README 已经更新了。

**Comment by upupming** [comment]
@Spades-S  另外现在 SM.MS V1 已经不能用了，后续等更新：
![image](https://user-images.githubusercontent.com/24741764/73606834-6b699700-45e9-11ea-9d52-52f9f73b833e.png)

**Comment by xiehongxin** [comment]
> @xiehongxin 已经更换 CI 为 GitHub Actions，可在这里下载最新版：https://github.com/PicGo/vs-picgo/actions/runs/33889307 ，README 已经更新了。

好的，谢谢啦
