### ISSUE TITLE
使用又拍云插入图片时缺少扩展名

### ISSUE THREAD

**Issue by YangXuran** [PicGo/vs-picgo#38]
`Picgo: Custom Output Format: <a data-fancybox="gallery" href="${url}"><img src="${url}!/max/1080"></a>`

输出为`<a data-fancybox="gallery" href="https://xxxx/2019/_DSC5489"><img src="https://xxxx/2019/_DSC5489!/max/1080"></a>`

又拍云侧文件名为_DSC5489

**Comment by upupming** [comment]
@YangXuran 我这里没有又拍云，还测试不了，又拍云自身会返回带拓展名的链接吗？

**Comment by YangXuran** [comment]
@upupming 这个不清楚，但是我可以新建一个Bucket与操作员授权，稍后将信息发送到您邮箱中可以吗？

**Comment by upupming** [comment]
嗯嗯，感谢，我的邮箱是 upupming@gmail.com
不过我暂时估计的是 `url` 本身不会出错，因为我们是直接从 PicGo-Core 拿到这个结果的，中间没有进行处理。
我来试看看吧~

**Comment by upupming** [comment]
@YangXuran 我这边是有拓展名的：
![upyun](https://user-images.githubusercontent.com/24741764/57440737-22afc800-727b-11e9-9b39-6b506b60a959.gif)

你能具体提供一下你全部的配置信息吗？

**Comment by upupming** [comment]
哦哦知道了，你的 `Custom Upload Name` 应该没加拓展名，我是这样的：
![image](https://user-images.githubusercontent.com/24741764/57442181-02353d00-727e-11e9-8bdf-357f9ebb2f4d.png)
修改一下，恢复成默认设置就行。

**Comment by upupming** [comment]
这里两个例子有点问题，我修改一下。

**Comment by YangXuran** [comment]
已解决，十分感谢
