### ISSUE TITLE
对 vscode 界面截图无法上传

### ISSUE THREAD

**Issue by chenxinlong** [PicGo/vs-picgo#40]
### Describe the bug

mac 下对 vscode 编辑器窗口进行截图，cmd+opt+u 右下角会弹出正在上传，然后没有任何上传结果。试了 smms 和七牛都是一样。

当截图内容不是 vscode 编辑器的时候可以正常上传，比如截浏览器的内容就是正常的。

### To Reproduce

重现方式同上述 description。

### System information

- OS: mac OSX
- Version  10.13.6

### VSCode information
安装插件之后，使用默认配置(即无修改任何 picgo 配置)。

- `vs-picgo` 2.0.4

**Comment by upupming** [comment]
Is there any error in the console？ Please provide them.

**Comment by chenxinlong** [comment]
对 vscode 编辑器进行截图，然后 cmd+opt+u，console 里显示内容如下图：
![image](https://user-images.githubusercontent.com/9261954/57970780-0ec14000-79b8-11e9-8320-93337fda83b7.png)

**Comment by upupming** [comment]
参加这个 issue https://github.com/Molunerfinn/PicGo/issues/199#issuecomment-471890683
下个版本会更新Core，可以不用再用这个workaround.
