### ISSUE TITLE
上传完成后data.json中不会插入图片？

### ISSUE THREAD

**Issue by lizhuangs** [PicGo/vs-picgo#41]
data.json使用的是picgo的配置，在vscode中插入图片后，这个文件没有更新uploaded节点，也就不能使用picgo管理图片了。

**Comment by upupming** [comment]
重读一下 README，你应该是设置的 `configPath` 而没有设置 `dataPath`。
<hr>
下次请按照 issue 模板来，提供必要的信息以供定位错误，谢谢。
