### ISSUE TITLE
vscode 中 腾讯 cos 无法指定路径

### ISSUE THREAD

**Issue by luwantaoChina** [PicGo/vs-picgo#44]
如果电脑中仅安装VS Code picgo 插件，那么就必须通过设置 pic bed 参数进行上传，然后这里 腾讯云 的参数字段中少了一个存储路径，这样就会导致文件直接上转到 存储桶而不是之下的目录中。我已经这样用了好久 :scream: :cry: :sob:

![temp-2019-6-10-20-48-37](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/images/temp-2019-6-10-20-48-37)

现在只能去下个picgo然后，通过这个设置指定上传路径：

![temp-2019-6-10-20-40-17](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/images/temp-2019-6-10-20-40-17)

望修复一下这个bug :sob:

## 还有一点建议

能不能上增加个功能在上转图片时，本地也指定个目录备份一下，因为我是用 snagit 截图，截图直接就在剪贴板里，然后就上传，本地 snagit 虽然有备份文件，但是命名之类很混乱。

**Comment by upupming** [comment]
1. 你的截图有问题，我这边显示不出来：
![image](https://user-images.githubusercontent.com/24741764/59234532-c8aa7580-8c1f-11e9-96af-bc6698128371.png)
2. 缺乏 vs-picgo 版本信息，我自己也用腾讯云，可以设置路径：
![image](https://user-images.githubusercontent.com/24741764/59234614-39519200-8c20-11e9-9670-cb99f584a86d.png)
等价于这里的：
![image](https://user-images.githubusercontent.com/24741764/59234630-4a9a9e80-8c20-11e9-9607-914f88b1b9ee.png)
3. 我觉得既然上传到云端了，就没有必要再做本地备份，另外 vs-picgo 后期也准备支持像 PicGo Electron 版那样的相册管理页面。

<hr>

请不要删除 issue 模板，谢谢。

**Comment by luwantaoChina** [comment]
感谢回复。
抱歉，删除了您的模板，下不为例。
我这边就是用2.0.4版的picgo啊，可是真没有Path这一参数项。

![README-2019-6-11-12-2-51.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/images/README-2019-6-11-12-2-51.png) :scream:

**Comment by upupming** [comment]
哈哈，抱歉是我搞错了，这个之前修复了 https://github.com/PicGo/vs-picgo/commit/606b9d42103aaf6ff56474315e3f8beae519fbcb ，但是还没有发布新版本。你可以先使用开发版，在 [README 里面](https://github.com/PicGo/vs-picgo#versioning)有说明。

**Comment by luwantaoChina** [comment]
好的，非常感谢
