### ISSUE TITLE
SM.MS V2 版 API 已经开放，支持个人空间，考量更新么?

### ISSUE THREAD

**Issue by stuarthua** [PicGo/vs-picgo#45]
如题，[https://sm.ms/doc/v2](https://sm.ms/doc/v2) sm.ms V2 版 API 已经开放，支持个人空间，目前只有 5G。但对想要管理个人图床的用户，或许是个选择，插件会考量更新目前的 sm.ms 上传插件么？

**Comment by upupming** [comment]
图片上传部分不由 `vs-picgo` 控制，你需要反馈到 https://github.com/PicGo/PicGo-Core 里面。
