### ISSUE TITLE
为什么修改了图床，还是使用sm.ms的

### ISSUE THREAD

**Issue by jerryc127** [PicGo/vs-picgo#46]
### System information

- OS: [e.g. Windows]
- Version [e.g. Windows 10]

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
  // Place you VScode `About` data here
  ```

- `vs-picgo` version

- Settings begin with `picgo`:

  ```json
  // ...
  "picgo.customUploadName": "${fileName}-${date}${extName}"
  // ...
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes/No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes/No.

```txt
If yes, please paste the error here.
```

为什么修改了图床，还是使用sm.ms的，已经改了github
![image](https://user-images.githubusercontent.com/16351105/66290863-ef995f80-e912-11e9-9d24-b170c5bd9e0d.png)

![image](https://user-images.githubusercontent.com/16351105/66290875-f88a3100-e912-11e9-9ec1-71867eb412d9.png)

![image](https://user-images.githubusercontent.com/16351105/66290910-0a6bd400-e913-11e9-9fcb-a57e7c43924e.png)

![image](https://user-images.githubusercontent.com/16351105/66290971-2bccc000-e913-11e9-9304-b8ba18d8be9d.png)

**Comment by upupming** [comment]
@jerryc127 Config Path 需要使用绝对路径而且会覆盖当前设置，请仔细阅读 [README](https://github.com/PicGo/vs-picgo/blob/dev/README.md)。
