### ISSUE TITLE
Mac 下从剪切板上传，总是会没反应！

### ISSUE THREAD

**Issue by buker2012** [PicGo/vs-picgo#47]
上传小窗口弹出来一下大概 1-2 秒，就关闭了，没有任何的错误提示。
有时候关掉 VS CODE 重开，可以上传，但是过一会儿又不行了。

**Comment by upupming** [comment]
@buker2012 铁一小报错信息，按照模板来。

**Comment by buker2012** [comment]
问题就在这，没有报错！没有任何报错！
![image](https://user-images.githubusercontent.com/22735530/66711690-45628180-edc3-11e9-8dec-b16e2ef17467.png)
就是这么一个进度条，1 秒后自动消失。。无报错！
我也很纳闷，是 github 图床。

**Comment by upupming** [comment]
@buker2012 是命令台的报错，按照 [ISSUE_TEMPLATE/bug_report.md](https://github.com/PicGo/vs-picgo/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md) 要求填写一下：
![image](https://user-images.githubusercontent.com/24741764/66711715-cde12200-edc3-11e9-8969-477a3b043c62.png)

**Comment by buker2012** [comment]
---
name: Bug report
about: Create a report to help us improve
title: '剪切板上传图片出错'
labels: ''
assignees: ''
---



### Describe the bug

Mac 下从剪切板中上传图片失败，使用文件上传是正常的。

### To Reproduce

1. 使用微信截图
2. VS 中使用剪切板上传

### Expected behavior



### Screenshots



### System information

- OS: Mac
- Version 10.13

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
    版本: 1.39.1
    提交: 88f15d17dca836346e787762685a40bb5cce75a8
    日期: 2019-10-10T23:35:11.314Z
    Electron: 4.2.10
    Chrome: 69.0.3497.128
    Node.js: 10.11.0
    V8: 6.9.427.31-electron.0
    OS: Darwin x64 17.7.0
  ```

- `vs-picgo` version 2.0.4

- Settings begin with `picgo`:

  ```json
  // ...
  "picgo.customUploadName": "${fileName}-${date}${extName}"
  // ...
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes.

```txt
[Extension Host] [PicGo ERROR]: Error creating a JP2 color space from ICC profile.Falling back to sRGB
```

**Comment by upupming** [comment]
这是 core 的问题，你可以使用这个解决办法 https://github.com/Molunerfinn/PicGo/issues/199#issuecomment-471890683

**Comment by upupming** [comment]
Duplicate of #40

**Comment by buker2012** [comment]
感谢，确实如此！
