### ISSUE TITLE
vscode远程开发使用PicGo时，Image not found in ClipBoard问题

### ISSUE THREAD

**Issue by CapsulE07** [PicGo/vs-picgo#48]
### Describe the bug

在远程开发状态下的vscode，选取目录中的图片，点击复制后，然后在编辑markdown页面中使用快捷键 ctrl+alt+u进行PicGo上传，会出现 Image not found in ClipBoard问题。有什么方法可以解决这种远程开发时剪切板的问题呢？
另外还有一个问题，我本地进行复制时，有什么办法可以将剪切板的图片同步到远程开发状态下服务器端的剪切板中？
同样的PicGo配置，本地vscode使用PicGo进行图片上传正常，即说明PicGo配置项是填入正确的。

### To Reproduce

1. 打开vscode成功连接远程服务器
2. 在vscode中点击图片文件，选择复制
3. 在vscode中markdown编辑页面中进行PicGo上传
4. 出现Image not found in ClipBoard提醒

### Screenshots

![image](https://user-images.githubusercontent.com/23300139/69596325-30714300-103d-11ea-840b-502311ef9e03.png)

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
 版本: 1.40.1 (system setup)
提交: 8795a9889db74563ddd43eb0a897a2384129a619
日期: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.1.7601
  ```

- `vs-picgo` version

- Settings begin with `picgo`:

  ```json
  // ...
  "picgo.customUploadName": "${fileName}-${date}${extName}"
  // ...
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes/No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes/No.

```txt
If yes, please paste the error here.
```

**Comment by upupming** [comment]
远程开发上传本地图片是不支持的，@Molunerfinn 说的是对的。

**Comment by CapsulE07** [comment]
感谢解答。

**Comment by lebron-bo** [comment]
![QQ截图20201231182534](https://user-images.githubusercontent.com/76761554/103437115-47319280-4c5e-11eb-83a8-da29928f3124.png)
我出现的这种问题可以解决嘛

**Comment by cxw620** [comment]
> 远程开发上传本地图片是不支持的，@Molunerfinn 说的是对的。

有办法能支持吗(来自网页版VSCode,即code-server)
