### ISSUE TITLE
github图床已设置完，网页无法显示已上传的图片

### ISSUE THREAD

**Issue by bbkali** [PicGo/vs-picgo#50]
在vscode已经配置好github图床，并且将图片上传到单独的rep中，并且在vscode 已经上传并产生图片链接![2020-1-2-17-52-39](https://raw.githubusercontent.com/bbkali/picbad/master/2020-1-2-17-52-39) ，但在网页中还是 无法显示该图片，是github rep中图片加载慢的原因么？

**Comment by Spades-S** [comment]
有可能是加载速度的问题，在浏览器里打开生成的图片链接速度怎么样

bb <notifications@github.com>于2020年1月3日 周五上午8:50写道：

**Comment by bbkali** [comment]
很慢，一时半会出不来.....有啥改进的办法么？

**Comment by bbkali** [comment]
浏览器访问该链接是可以直接下载的

**Comment by bbkali** [comment]
https://raw.githubusercontent.com/bbkali/picbad/master/2020-1-2-17-52-39

**Comment by bbkali** [comment]
是图片没有后缀名的缘故么？后缀名怎么默认都没有了么？

**Comment by upupming** [comment]
@bbkali 请贴一下 `settings.json` 里面的和 `vs-picgo` 有关的配置信息（不包括 token）。

**Comment by bbkali** [comment]
设置如下
![2020-1-3-9-50-40](https://raw.githubusercontent.com/bbkali/picbad/master/2020-1-3-9-50-40)
可以正常上传的github rep中 就是图片不带后缀 然后在博客网页中加载不出图片

**Comment by Spades-S** [comment]
@bbkail 
1. 不带后缀是可以解析出图片的 
![image](https://user-images.githubusercontent.com/18718461/71703538-154ddc00-2e10-11ea-84eb-26deb83e69ec.png)
2. 图片显示不出来大概率是网络的问题
- 不挂代理时
![image](https://user-images.githubusercontent.com/18718461/71703556-2f87ba00-2e10-11ea-9b7c-17aaeca93492.png)
- 挂代理时
![image](https://user-images.githubusercontent.com/18718461/71703574-44fce400-2e10-11ea-8778-24fc3df211ad.png)
3. 想避免因为GFW造成图片加载不出来，可以试试国内的CDN，七牛云这些

**Comment by bbkali** [comment]
好的 谢谢 我用了个代理试下也可以访问了
