### ISSUE TITLE
Failed to upload image in clipboard

### ISSUE THREAD

**Issue by TYZRPVX** [PicGo/vs-picgo#51]
版本: 1.41.1
提交: 26076a4de974ead31f97692a0d32f90d735645c0
日期: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Failed to upload image in clipboard

![image](https://user-images.githubusercontent.com/7645818/72135188-d516cc80-33c0-11ea-9339-6555e8795bc5.png)

**Comment by upupming** [comment]
Please follow the issue template, otherwise we cannot know what was happening.
