### ISSUE TITLE
mac vscode 上传图片后没有反应

### ISSUE THREAD

**Issue by menhuan** [PicGo/vs-picgo#56]
### Describe the bug

mac vscode 从剪切板上进行上传，上传完之后什么也不显示，使用的信息是七牛云，使用2.2.2Core上传是没有问题的

**Comment by upupming** [comment]
@menhuan 请按照issue模板提供一些信息，不然我们无法帮你定位错误

**Comment by menhuan** [comment]
### Describe the bug

mac vscode 从剪切板上进行上传，上传完之后什么也不显示，使用的信息是七牛云，使用2.2.2Core上传是没有问题的

### To Reproduce



1. 使用截图软件截图保存到剪切板上
2. 在vscode中使用快捷键上传
3. 上传显示upload image....
4. 然后上传结束后，没有反应在markdown文件中

### Expected behavior

我期待的是上传完毕后应该有具体的markdown形式的图片链接

### Screenshots



### System information

- OS: [mac]
- Version [10.13.6]

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
  // Place you VScode `About` data here
  ```

- `vs-picgo` version

- Settings begin with `picgo`:

  ```json
    "picgo.picBed.qiniu.accessKey": "zb-UWFMHmfBse-H_uj7jyJnoaocwv-YaZIKEQagS",
    "picgo.picBed.qiniu.bucket": "test",
    "picgo.picBed.qiniu.url": "yuming",
    "picgo.picBed.qiniu.path": "./img",
    "picgo.picBed.qiniu.secretKey": "secretKey",
    "picgo.picBed.current": "qiniu",
    "picgo.configPath": "/Users/ruiqi/Library/Application Support/picgo/data.json",
    "picgo.dataPath": "/Users/ruiqi/Library/Application Support/picgo/data.json",
    "picgo.customUploadName": "${fileName}-${date}-${extName}",
    "picgo.picBed.weibo.chooseCookie": false
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes/No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes/No.

```txt
没有任何提示错误
```

**Comment by upupming** [comment]
mac显示器设置的问题，参考之前关闭的issue，另外你上面的配置信息泄露了accessKey，请重新生成一个哈
