### ISSUE TITLE
在github上创建了token后，使用vs-picgo上传一次图片，github上的token就被自动删除了。

### ISSUE THREAD

**Issue by handbye** [PicGo/vs-picgo#58]
重复了好几次，都是如此。
环境是：mac os 10.15.3  vscode Version: 1.43.0 
这是token被删除后，github给我发的邮件，很奇怪啊，之前在windows上使用没遇到过这种情况。

![image](https://user-images.githubusercontent.com/26617058/76846465-82073d00-687b-11ea-94aa-977ac86e03c3.png)

**Comment by upupming** [comment]
是否安装了插件：https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync 需要自行删除一下

**Comment by handbye** [comment]
确实安装了这个插件，我明白了，感谢。

**Comment by alterhu2020** [comment]
应该是你的token密码被github检测到泄露，然后为了你的安全，他自动删除了这个泄露的token. 看看这个操作安装步骤： https://code.pingbook.top/blog/setup/how-picgo-vscode-setup.html#%E8%AE%BE%E7%BD%AEpicgo%E5%AF%B9%E5%BA%94%E7%9A%84github%E4%BB%93%E5%BA%93

**Comment by kktt007** [comment]
我之前用Settings Sync,把他自己同步的token放在其他仓库中,结果总是同步失败,后来才知道github检测token,发现立马gg

**Comment by ikingye** [comment]
我也遇到这个问题。。。那 sync 和 picgo 插件就无法共存了？

**Comment by upupming** [comment]
@ikingye VSCode 最新版不需要插件已经支持配置同步了，可以试试忽略 picgo 的配置：

![image](https://user-images.githubusercontent.com/24741764/96563235-4c846f80-12f4-11eb-8a5f-acf54d697490.png)

**Comment by ikingye** [comment]
@upupming 我配置了忽略，但是还是上传到 gist 了（我新建的 gist 进行测试）

```json
    // 这些配置不同步
    "settingsSync.ignoredSettings": [
        "picgo.picBed.github.token"
    ],
```

**Comment by upupming** [comment]
@ikingye 改为 `Spades.vs-picgo`

**Comment by ikingye** [comment]
@upupming 我看了一下，这个配置是 vscode 自己出的 sync（ote: Settings Sync is still in preview.）。所以不需要使用原先的 sync 插件。

![image](https://user-images.githubusercontent.com/29562589/96565650-3b892d80-12f7-11eb-91ac-5f8a31b99e08.png)

参考这里 https://code.visualstudio.com/docs/editor/settings-sync

**Comment by upupming** [comment]
@ikingye 感谢指出~

**Comment by handbye** [comment]
> @upupming 我看了一下，这个配置是 vscode 自己出的 sync，直接使用 github 账号登陆进行同步（Note: Settings Sync is still in preview.）。所以不需要使用原先的 sync 插件。
> 
> ![image](https://user-images.githubusercontent.com/29562589/96565913-8dca4e80-12f7-11eb-91bb-a632f31693f7.png)
> 
> 参考这里 https://code.visualstudio.com/docs/editor/settings-sync

你好，请教下如何忽略picgo的配置呢？

**Comment by ikingye** [comment]
@handbye 使用vscode自己的sync，就不需要忽略了，只要使用github账号登陆，就可以同步。
