### ISSUE TITLE
功能请求：图片重命名支持无中划线格式

### ISSUE THREAD

**Issue by ZanderZhao** [PicGo/vs-picgo#60]
vscode插件能否支持时间重命名无中划线，
+ 即【2020040418003030.jpg】
+ 而不是【2020-04-01-18-00-30-30.jpg】
目的想与客户端时间戳重命名格式一致
谢谢！

**Comment by upupming** [comment]
@ZanderZhao 

现在只支持这几个哈：

![image](https://user-images.githubusercontent.com/24741764/78669000-29711000-790e-11ea-93f0-92992a0e5f29.png)

客户端是指 PicGo Electron 版本吗？

**Comment by ZanderZhao** [comment]
@upupming 感谢回复，是Molunerfinn大佬这个https://github.com/Molunerfinn/PicGo/releases

**Comment by upupming** [comment]
@ZanderZhao 代码在这里，有需要的话欢迎 PR，之后有时间可能会一起改 :) 

https://github.com/PicGo/vs-picgo/blob/e8b30b72f5c68a0a31ea98302603968f85ab93bb/src/utils/index.ts#L19

我更倾向于把这几个数字暴露给用户，有没有横线由用户自己拼接。

**Comment by ZanderZhao** [comment]
@upupming 好的，谢谢！

**Comment by mouday** [comment]
这个还没改好吗，4年了，希望去掉横线，和客户端保持一致的命名

**Comment by jz0ojiang** [comment]
> 这个还没改好吗，4年了，希望去掉横线，和客户端保持一致的命名

你可以试试 `${dateTime.replaceAll(/-/g,'')}${extName}` 在当前版本有效（`v2.1.6`）
