### ISSUE TITLE
从剪切板上传图片失败

### ISSUE THREAD

**Issue by ybqu** [PicGo/vs-picgo#61]
您好，我目前使用插件版本2.1.0，vscode版本1.44.0，选择文件上传时可以，但是从剪切板中上传时显示成功，实际并没有上传，和没有复制图片直接上传效果一样，感觉应该是没有读取剪切板中的图片，由于之前的几个vscode版本也存在这个问题，我认为应该也不是vscode的问题，所以想问一下您如何解决，谢谢。

**Comment by upupming** [comment]
Duplicate of #40
