### ISSUE TITLE
文件上传名称问题

### ISSUE THREAD

**Issue by maoxfjob** [PicGo/vs-picgo#62]
请问我用的七牛，
想把名称配置成 20/02/02/ff1f2b88-bc38-42df-8d05-4f0c04fcab3b.png
并且日期后面文件名称要自动生成，
应该怎么处理？

**Comment by upupming** [comment]
@maoxfjob 前面的现在只支持年月日整体的一个字符串，后面的字符串生成规则你想要什么？md5么？

**Comment by upupming** [comment]
Duplicate of #60

**Comment by maoxfjob** [comment]
后面的字符串是UUID，保证文件名唯一
