### ISSUE TITLE
上传图片不成功，持续显示 img uploading | picGo always shows “img uploading”  but never finishs.

### ISSUE THREAD

**Issue by pickpikyup** [PicGo/vs-picgo#64]
### Describe the bug
OS： WIN10 WSL ubuntu and win10 
vs-picgo : 2.1.0
VScode  1.46

第一次使用picgo,　无法上传图片到smms图床, 　重启vs code后，images uploading 消失，重新上传不同图片的时候，出现相同问题，尝试多种图片格式，图片名字，都不能上传。。。

![image](https://user-images.githubusercontent.com/31985793/84767883-7e4a9a00-afd3-11ea-8172-b0e2fcfdc686.png)

**Comment by upupming** [comment]
请按照模板来填写，不然无法定位错误，谢谢

**Comment by godtang** [comment]
我也出现这个问题了，你是怎么处理的？

**Comment by purequant** [comment]
同样的问题，求解决

**Comment by upupming** [comment]
@purequant 新开一个issue，把具体配置和报错信息贴上

**Comment by godtang** [comment]
https://github.com/PicGo/vs-picgo/issues/67


> 同样的问题，求解决

https://github.com/PicGo/vs-picgo/issues/67
你可以看一下，配置是按ascii排序的，所以要先找到smms的配置项，添加token，就可以了
