### ISSUE TITLE
PicGo: image uploading

### ISSUE THREAD

**Issue by zjs1224522500** [PicGo/vs-picgo#66]
### 描述
- Copy and `Ctrl` + `alt` + `U`
![image](https://user-images.githubusercontent.com/17877010/87005627-e1ee6e80-c1f1-11ea-8ff7-f4d7cad497ee.png)
- 一直处于 Uploading 状态

### 配置
- 使用 Vscode-picgo 插件中的 Github 配置
![image](https://user-images.githubusercontent.com/17877010/87006088-ab652380-c1f2-11ea-8c17-a045c9120a83.png)

### 问题
- 请问如何定位问题产生的原因？或者如何查看日志信息

### 补充
- 从本地文件上传是没有问题的。 `Ctrl` + `alt` + `E`

**Comment by upupming** [comment]
请阅读issue模板，里面有查看错误日志的方法

**Comment by zjs1224522500** [comment]
### System information

- OS: Windows
- Version Windows 10

### VSCode information

- `Help` -> `About` -> `Copy`
```txt
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

### Additional context
![image](https://user-images.githubusercontent.com/17877010/87038920-feee6600-c220-11ea-9659-33af3787869e.png)
- `Help` -> `Toggle Developer tools`
```
log.ts:197   ERR spawn powershell ENOENT: Error: spawn powershell ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

- 请问这是什么原因呢？

**Comment by Molunerfinn** [comment]
设置一下powershell的环境变量，然后重启VSCode即可。https://github.com/Molunerfinn/PicGo/issues/279#issuecomment-496368283
