### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by godtang** [PicGo/vs-picgo#67]
### To Reproduce

1. 截图
2. CTL+ALT+U
3. 始终是uploading

### Expected behavior
上传成功，和介绍的GIF图一样，自动粘贴MARKDOWN地址

### Screenshots
![image.png](https://i.loli.net/2020/07/15/w2ymI6h8sZaDz4L.png)

### System information

- OS: [Windows]
- Version [Windows 10 10.0.18362 暂缺 Build 18362]

### VSCode information

- `Help` -> `About` -> `Copy`

 ```txt
版本: 1.47.1 (user setup)
提交: 485c41f9460bdb830c4da12c102daff275415b53
日期: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
 ```

- `vs-picgo` version
v2.1.0

- Settings begin with `picgo`:
默认设置，无任何修改
  ```json
  // ...
  "picgo.customUploadName": "${fileName}-${date}${extName}"
  // ...
  ```

### Additional context
[PicGo ERROR]: Error: Can't find smms config, please provide api token, see https://sm.ms/home/apitoken
![image.png](https://i.loli.net/2020/07/16/clyi1W5U8hTPqa4.png)

### 个人推测
1. 在[https://sm.ms/](https://sm.ms/)上直接CTL+V，可以得到对应的网址
2. 通过fiddler抓包，PicGo还没有往sm.ms上传图片

**Comment by godtang** [comment]
![image.png](https://i.loli.net/2020/07/15/w2ymI6h8sZaDz4L.png)

**Comment by upupming** [comment]
请按照issue模板来，不然无法判断问题所在

**Comment by godtang** [comment]
> 请按照issue模板来，不然无法判断问题所在

你好，已经按照要求修改

**Comment by upupming** [comment]
additional comtext里面关键的 devtools 里面的 console 报错要贴一下，issue模板有怎么获取的指导。

**Comment by godtang** [comment]
> additional comtext里面关键的 devtools 里面的 console 报错要贴一下，issue模板有怎么获取的指导。

已经添加了
[PicGo ERROR]: Error: Can't find smms config, please provide api token, see https://sm.ms/home/apitoken
![image.png](https://i.loli.net/2020/07/16/clyi1W5U8hTPqa4.png)

**Comment by upupming** [comment]
smms需要配置token的，自己看一下文档和vscode setting的注释
