### ISSUE TITLE
上传失败！服务器出错，请重试

### ISSUE THREAD

**Issue by DeeliN-uno** [PicGo/vs-picgo#69]
### System information

- OS: [e.g. Windows]
- Version [e.g. Windows 10]

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
  // Place you VScode `About` data here
  ```

- `vs-picgo` version

- Settings begin with `picgo`:

  ```json
  // ...
  "picgo.customUploadName": "${fileName}-${date}${extName}"
  // ...
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes/No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes/No.

```txt
If yes, please paste the error here.
```

**Comment by upupming** [comment]
Please fill in the issue template, otherwise, we cannot see what went wrong.
