### ISSUE TITLE
macos: command 'picgo.uploadImageFromExplorer' not found

### ISSUE THREAD

**Issue by enderson-pan** [PicGo/vs-picgo#70]
### Describe the bug
macos vscode 按下command+option+e，报错说上传命令没有找到
<img width="446" alt="image" src="https://user-images.githubusercontent.com/1694834/90814307-7c96ad00-e35b-11ea-9855-2b809a327886.png">

### VSCode information
```txt
 Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:09:41.484Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0
```
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/1694834/90813925-e19dd300-e35a-11ea-89b5-4e8f4cd3ab52.png">

**Comment by upupming** [comment]
Please fill in the issue template.
