### ISSUE TITLE
vs-picgo使用picgo配置文件剪切板上传成功，但无反应

### ISSUE THREAD

**Issue by 421696067** [PicGo/vs-picgo#75]
## 描述错误：vs-picgo使用picgo配置文件剪切板上传成功，但无反应

          vscode环境：
          版本: 1.52.1
          提交: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
          日期: 2020-12-16T16:34:46.910Z
          Electron: 9.3.5
          Chrome: 83.0.4103.122
          Node.js: 12.14.1
          V8: 8.3.110.13-electron.0
          OS: Windows_NT x64 10.0.17763

#### picgo配置：
![image](https://user-images.githubusercontent.com/16398564/103157190-7a51cd00-47eb-11eb-8efa-6387867af0f3.png)

####  vs-picgo:配置
![image](https://user-images.githubusercontent.com/16398564/103157334-c0f3f700-47ec-11eb-81b1-d11ac861a1f3.png)

> picgo使用功能全部正常，vs-picgo使用vscode内部设置 剪切板和文件上传也全部正常
但是如果vs-picgo中使用picgo的data.json文件，按Ctrl+Alt+U剪切板上传显示成功，但是没有反应，其他的文件上传功能还是OK的，

### vs dev tools 报错如下
![image](https://user-images.githubusercontent.com/16398564/103157451-d7e71900-47ed-11eb-8290-74adfcbc5ed6.png)

### 清除tools中的consle再次剪切板上传，报错如下
![image](https://user-images.githubusercontent.com/16398564/103157525-986cfc80-47ee-11eb-923a-03cd3ae2ff8b.png)

![image](https://user-images.githubusercontent.com/16398564/103157540-baff1580-47ee-11eb-819d-d1c37d5d6e9b.png)

期间更换过电脑，现象依旧。

**Comment by upupming** [comment]
macOS 无法复现这个问题，我尝试一下 Windows

**Comment by upupming** [comment]
和这个错误是一样的：https://github.com/PicGo/PicGo-Core/issues/32#issuecomment-597025456
![image](https://user-images.githubusercontent.com/24741764/103198774-2696cf00-4924-11eb-8962-1d4d3efe9658.png)
PicGo-Core 已经修复了这个，我们只需要更新一下版本就行了：https://github.com/PicGo/PicGo-Core/pull/35/files

马上会进行一下修复

**Comment by upupming** [comment]
PicGo 版本在 1.4.8 修复这个问题：https://github.com/PicGo/PicGo-Core/blob/dev/CHANGELOG.md#tada-148-2020-04-04

**Comment by upupming** [comment]
Bug 出在这一行，我们不需要配置文件里面的 `GUI` 模式：
https://github.com/PicGo/PicGo-Core/blob/master/src/utils/getClipboardImage.ts#L30

**Comment by upupming** [comment]
@421696067 问题已经修复，请下载最新版 vsix 安装包手动安装：https://github.com/PicGo/vs-picgo/actions/runs/449033628

将会在下个 release 发布

**Comment by upupming** [comment]
Windows 平台下，PicGo-Electron 的文件全都在 `C:\Users\你的用户名\AppData\Roaming\picgo` 下。 https://picgo.github.io/PicGo-Doc/zh/guide/config.html

在 PicGo-Electron 里面初始化 `picgo` 的时候[指定了 `configPath` 为 `C:\Users\你的用户名\AppData\Roaming\picgo`](https://github.com/Molunerfinn/PicGo/blob/2129f86266bcc88eda4c48c9c68e931d6e4fd100/src/main/apis/core/picgo/index.ts#L13)，因此 使用 GUI 模式，运行脚本才没问题[能够找到 Roaming 下的脚本](https://github.com/PicGo/PicGo-Core/blob/210956a486bd34ebbaff95669096a66f7e361128/src/utils/getClipboardImage.ts#L35)。

CLI 应用不应该去依赖 Electron 的脚本（在这个 Bug 中就是 vs-picgo 在使用 picgo-core 的时候没有指定 configPath，picgo-core走到 GUI 的逻辑到 `C:\Users\你的用户名\.picgo\` 之下去找脚本了，找不到脚本，运行了空脚本就报错了），CLI 应用应该都需要使用 node_modules 里面 `picgo` 自带的脚本，将 PICGO_ENV 置为 `CLI` 是最好的选择。

**Comment by 421696067** [comment]
感谢 感谢  安装vsix插件后，已修复，Webpack 是这样添加？不添加也正常了呢。
![image](https://user-images.githubusercontent.com/16398564/103271476-51048d00-49f5-11eb-9347-5905a66bab78.png)

**Comment by upupming** [comment]
@421696067 添加webpack是指我们的代码里面加了这个，作为使用者不需要操心哈
