### ISSUE TITLE
关于自定义链接问题

### ISSUE THREAD

**Issue by Chao-bei** [PicGo/vs-picgo#76]
您好，我现在使用的PicGo版本是2.3.0 beta 3，在自定义链接格式中，强制要求含有$url，但是这在使用CDN（jsDelivr）时，完全不需要原始链接，想问下您可否通过配置文件取消这个限制？

**Comment by upupming** [comment]
@Chao-bei 是不是走错 repo 了？这个仓库是 `vs-picgo` 不是 PicGo 哈，可以到这里反馈：https://github.com/Molunerfinn/PicGo/issues/

**Comment by Chao-bei** [comment]
不好意思，走错了。。。。
