### ISSUE TITLE
[help wanted] How can I make vs-picgo work behind the proxy?

### ISSUE THREAD

**Issue by Rullec** [PicGo/vs-picgo#79]
Hi guys,
    
Thanks a lot for your work on this awesome plugin, I really benifit a lot from it ;-)
    
I work with `vscode` (`vs-picgo 2.1.0` has been installed, and the image bed is `github`) on `Ubuntu 18.04 LTS`. How can I enable the proxy for the uploading procedure in it? Does it follow the system proxy settings? Is there anything I can do to customize it?
    
Thanks a lot!

**Comment by upupming** [comment]
@Rullec Thanks for the feedback. You can just add this configuration to your VSCode Settings as per [the docs](https://picgo.github.io/PicGo-Core-Doc/zh/guide/config.html#picbed-proxy):

```json
"picgo.picBed.proxy": "127.0.0.1:1081"
```

Although this config is not listed on the settings page and you will get a warning like a picture below, but it is totally fine as `vs-picgo` will read all configurations under the `picgo.picBed` and pass it to `picgo-core`:

![image](https://user-images.githubusercontent.com/24741764/104426739-49c8ac00-55bd-11eb-8c05-a18da0b4cc52.png)

We will add this configuration to the settings page in the next release~

**Comment by Rullec** [comment]
> 
> We will add this configuration to the settings page in the next release~

@upupming  Thanks for your quick response and guidance! 

Now I can upload my images happily, even **potentially without the proxy setting**. 

Though It doesn't effect the functionality, I still post it here just in case.

***

- Just now, I tried to paste an image from clipboard to vscode by the shortcut `ctrl + alt + U` **without the proxy setting**, and It **WORKS WELL**.

- Then as you said, I added `picgo.picBed.proxy` in my global `settings.json` manually (I confirm my http proxy work behind the local port `12333`). as shown below:
```
    "picgo.picBed.current": "github",
    "picgo.picBed.github.branch": "main",
    "picgo.picBed.github.path": "vscode/",
    "picgo.picBed.github.repo": "XXXXXXXXXXXX",
    "picgo.picBed.github.token": "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "picgo.customUploadName": "${dateTime}${extName}",
    
    "picgo.picBed.proxy" : "127.0.0.1:12333",
```
- kill and reopen the `vscode`.
- Then I do the copy-paste work again in `vscode`, and monitoring the proxy log in another window. It seems the `picgo` doesn't use the proxy...
![image](https://user-images.githubusercontent.com/16875930/104449976-645d4e00-55da-11eb-9da1-fcab7cb73dc1.png)

**Comment by upupming** [comment]
@Rullec Nice caught up!

Sorry for the wrong configuration, instead of `127.0.0.1:1081`, you should use `http://127.0.0.1:1081` like below:

```js
"picgo.picBed.proxy": "http://127.0.0.1:1081",
```

Here is my test result:

![image](https://user-images.githubusercontent.com/24741764/104468074-03417480-55f2-11eb-8e0e-0b71490c7a79.png)

And the `proxy` is corrected passed to picgo-core (I add a `console.warn` to see what config is passed in):

![image](https://user-images.githubusercontent.com/24741764/104468235-2c620500-55f2-11eb-9271-e3ee5b3c7047.png)

<hr>

The reason why the wrong configuration can still work may due to GitHub is sometimes fast and sometimes slow in the EDU network. You can change the configuration to the corrected version and try to see your proxy tool's log again. If you have any problems, please fell free to post here again.

**Comment by Rullec** [comment]
@upupming  Thank you very much for the patience! I'm sorry to reply this closed issue again, cuz there is still a tiny problem for me to ask ;-)

> due to GitHub is sometimes fast and sometimes slow in the EDU network.

Yes! It must be the duty of `ZJUWLAN` ;-), you know....

> you should use `http://127.0.0.1:1081`

I will add the prefix `http://` in front of my localhost in the `settings.json`  tomorrow morning, in order to have a quick test.

***
# A problem / question for curiosity
I'm really curious about the screenshot you posted above, it's:
![image](https://user-images.githubusercontent.com/16875930/104484450-4a386580-5604-11eb-80df-2136d2f9b84b.png)

Because of the lackness of knowledge of the frontend, I felt hard to recognize where I can get this console. Would you be happy to give me some insight?

Thanks a lot!

**Comment by upupming** [comment]
@Rullec 
> I felt hard to recognize where I can get this console. Would you be happy to give me some insight?

This is just my test to confirm that `proxy` will work although it is not listed on the settings page. If you want to have a test, too, here are the steps:

1. Open file `~/.vscode/extensions/spades.vs-picgo-2.1.0/out/src/vs-picgo/index.js`, this is the place where the plugin is installed to.
2. Goto line 47 or search for `const picBed = vscode.workspace.getConfiguration('picgo.picBed');`
3. Add `console.warn('picBed', picBed)`
    ![image](https://user-images.githubusercontent.com/24741764/104533255-0027a200-564d-11eb-9f35-0295f2192683.png)
4. Kill and restart VSCode and test uploading again, and with developer tools (Help -> Toggle Developer Tools) open to see the log.

**Comment by Rullec** [comment]
Thanks!

**Comment by upupming** [comment]
https://github.com/PicGo/PicGo-Core/issues/64

**Comment by Molunerfinn** [comment]
try picgo-core 1.4.16

**Comment by upupming** [comment]
> try picgo-core 1.4.16

Nice, thanks!

**Comment by upupming** [comment]
Close as no response, please feel free to open a new issue if still has trouble.
