### ISSUE TITLE
能不能把插件上传的图片显示到picgo的相册中

### ISSUE THREAD

**Issue by glamourzc** [PicGo/vs-picgo#8]
如题，能不能把插件上传的图片显示到picgo的相册中

**Comment by upupming** [comment]
@glamourzc We are working at #14 now, any suggestion is welcome~

**Comment by upupming** [comment]
Solved by v2.0.0
Nightly build v2.0.0 is available at https://ci.appveyor.com/project/upupming/vs-picgo/build/artifacts, any feedback is welcome!

**Comment by thulc** [comment]
### v2.1.6 插件上传的图片仍然无法显示到picgo的相册中
My environment:
- macOS
- picgo 2.3.0
- vs-picgo 2.1.6

I config the vs-picgo according to the README file as below 
[我的配置信息](https://raw.githubusercontent.com/achang658/img-bed/main/2022/02/%E6%88%AA%E5%B1%8F2022-02-15%2012.08.05-cfd434.png)，and I use the setting file data.json of my picgo electron to config the vs-picgo. However, I still can not see the pic uploaded by vs-picgo showing in the photo album of picgo electron. I'm wandering what casued this problem. Thank you!
