### ISSUE TITLE
[Feature Request] [Ubuntu] Recognize and upload the image with the shortcut when the image path is copied in the clip board 

### ISSUE THREAD

**Issue by Rullec** [PicGo/vs-picgo#80]
Hi all!
   After this period of use, I found that the `vs-picgo` plugin make me reaaaaly more productive, I love it a lot!
   But on `Ubuntu 18.04` I would like to have a very personal feature request.

# 1. Background
As you know, the default file explorer in `Ubuntu` is typically `nautilus`, and the copy action in `nautilus` do not put the media file into the clipboard. Alternatively, it actually ONLY copy the file path, as indicated by [this post](https://askubuntu.com/questions/1132689/ubuntu-18-04-nautilus-copy-image-instead-of-path)

# 2. The feature(or option) I would like to have
When I copy an image(no matter `.png` or `.gif`) in the `nautilus` and want to upload it in `vscode` by `vs-picgo`, I cannot use my familiared short cut `ctrl + alt + U` to acheive this, because there is only a file path, briefly a `string` lying inside of the clipboard.

What I can do is only open the palette, and select the other two ways to upload it, like the image shown below
![image](https://user-images.githubusercontent.com/16875930/104716976-9cdc6380-5763-11eb-9608-61d697d2c3ac.png)

May I make the `ctlr + alt + U` command to cover this functionality as well? In another word, I hope that when `ctrl + alt + U` is triggered and the `vs-picgo` find it an image path, the selection & uploading procedure can be automatically done.

Or if you find it trivial, may I have an option to do this? This feature can really keep the workflow simply and make the user happy.

***
I know that this may be very personal, so feel free to close it if you find it not quite useful, or add it into the waiting list ;-)

Thanks a lot for all of your work!

**Comment by upupming** [comment]
@Rullec Could you please show me the output of Developer Tools? 
From what I know, you have to install `xclip` in Linux for the `copying for the clipboard` to work. See https://github.com/Molunerfinn/PicGo/issues/285 for more detail. 

----

I think `vs-picgo` should have reported the xclip is not installed error, I will try to add the error dialog next time.
