### ISSUE TITLE
windows 下剪贴板上传成功但实际未上传

### ISSUE THREAD

**Issue by xmu714** [PicGo/vs-picgo#85]
### Describe the bug

截图保存到剪贴板以后，通过插件的快捷键显示成功上传，但是没有给出图片链接，图床上查了也没有上传上去
选择文件上传正常

### To Reproduce

1. 设置默认图床阿里云OSS
2. 截图保存到剪贴板
3. 使用快捷键`Ctrl+Alt+U`上传
4. 显示上传成功，但是链接没有显示出来

### Expected behavior

上传图片并给出正确链接

### System information

- OS: Windows
- Version: Windows 10

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
  // Place you VScode `About` data here
  版本: 1.56.2 (user setup)
  提交: 054a9295330880ed74ceaedda236253b4f39a335
  日期: 2021-05-12T17:13:13.157Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Windows_NT x64 10.0.19043
  ```

- `vs-picgo` version

- Settings begin with `picgo`:

  ```json
  // ...
  "picgo.customUploadName": "${fileName}${extName}"
  // ...
  ```

### Additional context

目前我只用了OSS图床，其他没测试

```txt
(node:616) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 failed listeners added to [PicGo]. Use emitter.setMaxListeners() to increase limit

[PicGo ERROR]: read file Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6 error
```

**Comment by upupming** [comment]
@xmu714 请给出具体错误的截图，或者包含出错代码地址的日志，这个看不到具体出错的地方

**Comment by upupming** [comment]
Duplicate of #89
