### ISSUE TITLE
从剪贴板上传图片失败

### ISSUE THREAD

**Issue by ChaoXu1997** [PicGo/vs-picgo#86]
### Describe the bug

配置githb为图床，从剪切板上传图片失败，但是出现bug的前一天还可以成功上传
![image](https://user-images.githubusercontent.com/72029457/120627032-d48b4400-c495-11eb-9d67-40c7ba1045e7.png)

### To Reproduce

1. 打开markdown.md文件，用截屏软件截图复制在剪切板
2.光标处在md文件中，ctrl+alt+u
3.显示从剪切板上传失败
![image](https://user-images.githubusercontent.com/72029457/120627450-45caf700-c496-11eb-8601-27eeeadaaa8c.png)

### Expected behavior

图片成功上传github，在md文件中返回md图片格式链接
### System information
Linux ubuntu 5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
 Version: 1.57.0-insider (user setup)
Commit: 217f1a2f60a197807de78af362ecb832100fda96
Date: 2021-06-02T06:36:06.263Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042// Place you VScode `About` data here
  ```

- `vs-picgo` version

- Settings begin with `picgo`:

  ```json
  // ...
 
    
  // ...
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes/No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes/No.

```txt
If yes, please paste the error here.
```

**Comment by upupming** [comment]
请按照模板报issue
