### ISSUE TITLE
远程连接剪切板不支持 Running the contributed command: 'picgo.uploadImageFromClipboard' failed.

### ISSUE THREAD

**Issue by ChaoXu1997** [PicGo/vs-picgo#87]
使用vs-picgo：v2.1.0时遇到报错：Running the contributed command: 'picgo.uploadImageFromClipboard' failed.

**Comment by ChaoXu1997** [comment]
![image](https://user-images.githubusercontent.com/72029457/120638700-0951c800-c4a3-11eb-9f2f-098e0e9ee6ea.png)

**Comment by upupming** [comment]
从截图来看，应该是网络问题，github现在不是很稳定，建议用其他图床

**Comment by upupming** [comment]
或者使用代理

**Comment by ChaoXu1997** [comment]
我发现问题了，我远程连接的服务器，本地的剪切板与远程不同步导致我一直上传失败

**Comment by ChaoXu1997** [comment]
但是远程开发有什么办法使用vs-picgo吗

**Comment by upupming** [comment]
@ChaoXu1997 暂时不支持远程连接的

**Comment by upupming** [comment]
Duplicate of #90
