### ISSUE TITLE
上传GitHub成功但是不自动生成链接

### ISSUE THREAD

**Issue by JeffersonQin** [PicGo/vs-picgo#88]
### Describe the bug

图片能够成功上传至GitHub, 但是不会自动生成链接

### Screenshots

![image](https://user-images.githubusercontent.com/30655701/124443856-9e045a00-ddb0-11eb-898d-140930eb1b7a.png)

### System information

- OS: Windows
- Version: Windows 10.0.19042

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
  Version: 1.56.2 (system setup)
  Commit: 054a9295330880ed74ceaedda236253b4f39a335
  Date: 2021-05-12T17:13:13.157Z
  Electron: 12.0.4
  Chrome: 89.0.4389.114
  Node.js: 14.16.0
  V8: 8.9.255.24-electron.0
  OS: Windows_NT x64 10.0.19042
  ```

- `vs-picgo` version: 2.1.0

- Settings begin with `picgo`:

  ```json
  "picgo.picBed.current": "github",
  "picgo.picBed.github.branch": "master",
  "picgo.picBed.github.customUrl": "https://cdn.jsdelivr.net/gh/JeffersonQin/blog-asset@latest",
  "picgo.picBed.github.path": "usr/picgo/",
  "picgo.picBed.github.repo": "JeffersonQin/blog-asset",
  "picgo.customOutputFormat": "![](${url})",
  ```

**Comment by upupming** [comment]
报错写的服务端出错，应该是GitHub的网不太好，可以挂一下梯子。
