### ISSUE TITLE
[PicGo ERROR]: read file Windows PowerShell

### ISSUE THREAD

**Issue by sunsteam** [PicGo/vs-picgo#89]
阿里云oss上传截切板图片失败，情况类似 issue #85 ，他写过的内容我就不重复了，补一下console的图

另外，直接用picGo的GUI上传剪切板图片是成功的，只有插件的CTRL ALT U 上传有问题

- `vs-picgo` version

2.1.0，直接从VS插件库中安装的

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?**  未尝试其他图床

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes

![image](https://user-images.githubusercontent.com/7489390/126585474-f9368172-cff9-4ce6-ac66-dfada6310a63.png)

贴一下我power shell版本信息

![image](https://user-images.githubusercontent.com/7489390/126585580-0a46b352-3c66-4ce2-8169-5fd55a809948.png)

**Comment by upupming** [comment]
@sunsteam read file error 参考 https://github.com/PicGo/PicGo-Core/blob/85ecd16253ea58910de63511ea95e6f6fb6249d6/src/utils/common.ts#L59 ，估计是这里抛出的错误

我的版本和你一样但是没有报错：

![image](https://user-images.githubusercontent.com/24741764/126899692-3b4cf9b7-7744-491f-bf19-68f2aa91a129.png)

![image](https://user-images.githubusercontent.com/24741764/126899700-6e04c168-41e0-422e-9ead-24035199968f.png)

可以麻烦你调试一下吗，具体的做法是打开文件 ` C:\Users\你的用户名\.vscode\extensions\spades.vs-picgo-2.1.0\node_modules\picgo\dist\src\plugins\transformer\path.js`，在这里加一行：

```js
console.log(`${item} is trouble maker`);
```

![image](https://user-images.githubusercontent.com/24741764/126900072-db4f3eec-6db5-4e5f-9e82-512482f91b6c.png)

然后看一下控制台输出的是什么

**Comment by sunsteam** [comment]
![image](https://user-images.githubusercontent.com/7489390/126903329-23445226-57ac-42e0-8d38-ae3c1f74dbf4.png)

@upupming  按你的要求如图

**Comment by upupming** [comment]
@sunsteam 麻烦也打印一下 `item` 看看呢：

![image](https://user-images.githubusercontent.com/24741764/126900072-db4f3eec-6db5-4e5f-9e82-512482f91b6c.png)

```js
console.log(`${item} is trouble maker`);
```

**Comment by upupming** [comment]
> ![image](https://user-images.githubusercontent.com/7489390/126903329-23445226-57ac-42e0-8d38-ae3c1f74dbf4.png)
> 
> @upupming 按你的要求如图

这个报错是 `fs` 的报错， fs 读取文件出错就会抛出这个错误，例如：

![image](https://user-images.githubusercontent.com/24741764/126903960-58353fb9-8d23-443e-a92b-22c8c5cec09a.png)

看这个报错，传给 fs 的文件名居然是 powershell 这一串路径，想起来了这个问题已经修复过了，是这个：https://github.com/PicGo/vs-picgo/issues/75

**Comment by upupming** [comment]
我待会会发一个包，修复了一下 Bug 但是还没有发过包，导致大家一直问一样的问题，时间太久我也忘记了 😅

**Comment by upupming** [comment]
已发包，请更新最新版 vs-picgo 2.1.2 使用
