### ISSUE TITLE
wsl upload fail

### ISSUE THREAD

**Issue by xnng** [PicGo/vs-picgo#90]
wsl 中上传到 oss 失败

通过 vsocde remote wsl 上传时会出现此错误

![image](https://user-images.githubusercontent.com/38936252/126597571-30389fb0-da9c-41f0-89a8-f4c0bd51ec13.png)

wsl 用的是 Ubuntu 20.04

**Comment by upupming** [comment]
@xnng wsl 现在还不支持，没有测试过，如果直接在非wsl环境下应该没问题吧

**Comment by xnng** [comment]
@upupming 可能跟 #87 是同一个问题，vscode 是通过 remote 的方式连接到 wsl 中的，如果直接在 windows 环境中使用是没有问题的

**Comment by upupming** [comment]
@xnng 嗯嗯，因为远程机器的剪切板和本地的是不一样的，这个还不确定能不能让远程的机器获取本地机器的内容，只有一个 https://code.visualstudio.com/api/references/vscode-api#Clipboard 是用来获取文本的。

**Comment by JeffersonQin** [comment]
WSL下可以用过Windows的命令获取剪切板，这里个人认为可以通过subprocess的方式获得。

举例：
```bash
powershell.exe Get-Clipboard
```

获取图片：
```bash
powershell.exe Get-Clipboard -Format Image
```

![image](https://user-images.githubusercontent.com/30655701/127095303-74213318-2b31-44ce-9e8b-e24e293f35c9.png)

**Comment by upupming** [comment]
好的，后续会看一下

**Comment by JeffersonQin** [comment]
@upupming 我前面测试了一下想法，基本上解决了。今天晚上我往PicGo-Core提一个PR，还请您到时候看一下。

**Comment by upupming** [comment]
@JeffersonQin 太强了，欢迎 PR！
