### ISSUE TITLE
command uploadImageFromXXX not found on Ubuntu20.04 via VsCode 1.58.2

### ISSUE THREAD

**Issue by Seven-Steven** [PicGo/vs-picgo#91]
### Describe the bug
I installed the plugin vs-picgo on VsCode 1.58.2, but can't upload images. 
The error message shows "command uploadImageFromXXX not found".

### To Reproduce

1. Go to markdown file;
2. Click on `ctrl + alt + U` or `ctrl + alt + E` or `ctrl + alt + O`;
3. See error: "command uploadImageFromXXX not found".

### Screenshots

![image](https://user-images.githubusercontent.com/13358658/126894227-a9a44c28-b067-4891-8df1-ac8b178eeb7d.png)

- OS: Ubuntu
- Version 20.04

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
    版本: 1.58.2
    提交: c3f126316369cd610563c75b1b1725e0679adfb3
    日期: 2021-07-14T22:30:16.440Z
    Electron: 12.0.13
    Chrome: 89.0.4389.128
    Node.js: 14.16.0
    V8: 8.9.255.25-electron.0
    OS: Linux x64 5.8.0-59-generic
  ```

- `vs-picgo` version
  2.1.0

- Settings begin with `picgo`:

  ```json
    "picgo.configPath": "/home/seven/.picgo/config.json",
  ```

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: No.

**Comment by upupming** [comment]
@Seven-Steven 控制台没有任何报错吗？

**Comment by Seven-Steven** [comment]
@upupming 感谢回应。
我先打开控制台，清空与 picgo 插件无关的警告信息，然后在 markdown 文件中依按下快捷键 `ctrl + alt + U` or `ctrl + alt + E` or `ctrl + alt + O`，屏幕右下角会弹出错误提示，但是控制台没有任何新增报错。

补充：
1. 我电脑先前安装过命令行版本的 picgo-core，并且将其配置到 Typora 中，可以正常使用且体验良好，不知道 vscode 插件和命令行版本的 picgo-core 是否会有冲突；
2. 我公司还有一台 Ubuntu 19.10 系统的电脑，明天上班我再安装一下 vs-picgo 试试看行不行。

**Comment by upupming** [comment]
@Seven-Steven 刚刚发了一个包 2.1.1，可以先尝试更新一下

1. 全局的 picgo-core 和 vs-picgo 自带的不会有任何冲突，这个不必担心
2. 我看你的控制台完全空白，没有任何信息这不是很正常，正常来说各种插件啥的总会打印一点东西的

**Comment by Seven-Steven** [comment]
@upupming 更新到 2.1.1 之后控制台会显示报错信息，如下：
![image](https://user-images.githubusercontent.com/13358658/126908176-22688126-8506-43f7-9780-13062a8f4ba6.png)

**Comment by upupming** [comment]
@Seven-Steven 看到错误了，打包出了点问题，明天再发个包修复一下

**Comment by Seven-Steven** [comment]
@upupming 好的，麻烦您了

**Comment by upupming** [comment]
@Seven-Steven 已经放在 GitHub Release 了：https://github.com/PicGo/vs-picgo/releases/tag/v2.1.2 ，明早我再请 @Spades-S  更新一下 VSCode Marketplace

**Comment by Seven-Steven** [comment]
@upupming 感谢深夜帮我问题。

## 验证
我更新了 vs-picgo 2.1.2 版本，在完全使用默认配置的情况下，sm.ms 图床可以正常使用。
![image](https://user-images.githubusercontent.com/13358658/126909795-e68b2896-0c68-4537-9225-c3c2cc1170b5.png)

但我这边有一些额外的需求。
## 背景
在我单独安装的 picgo-core 中，我通过 “picgo-plugin-web-uploader" 插件配置了自定义图床（不在默认提供的图床列表之内）。我的 `.picgo/config.json` 文件如下：
```json
{
  "picBed": {
    "current": "web-uploader",
    "web-uploader": {
      "customBody": null,
      "customHeader": null,
      "url": "XXXXXXXXXXXXXXXXXXXXXXX",
      "paramName": "file",
      "jsonPath": "data.o_url"
    }
  },
  "picgoPlugins": {
    "picgo-plugin-web-uploader": true
  }
}
```
上述配置在命令行和 Typora 中都是验证正常可用的。

## 问题
如果我在 vs-picgo 的配置中指定 picgo 的配置文件为 `/home/seven/.picgo/config.josn`, 也就是上面提到的自定义配置：
![image](https://user-images.githubusercontent.com/13358658/126909932-a8d48470-38d3-4640-9ef4-d4e30cc0bcd4.png)
控制台会提示 ”Can't find smms config", 导致无法上传图片。

![image](https://user-images.githubusercontent.com/13358658/126909960-3d5a9cea-a1af-4429-8035-94f9dad7da1b.png)

## 诉求
请问 vs-picgo 插件能否支持自定义图床呢？无需在 vs-code 中配置自定义图床，只需要能够使用我的 picgo-core 的配置文件即可。

再次感谢！

**Comment by Spades-S** [comment]
> @Seven-Steven 已经放在 GitHub Release 了：https://github.com/PicGo/vs-picgo/releases/tag/v2.1.2 ，明早我再请 @Spades-S 更新一下 VSCode Marketplace

done

**Comment by Spades-S** [comment]
> @upupming 感谢深夜帮我排查和解决问题。
> 
> ## 验证
> 我更新了 vs-picgo 2.1.2 版本，在完全使用默认配置的情况下，sm.ms 图床可以正常使用。
> ![image](https://user-images.githubusercontent.com/13358658/126909795-e68b2896-0c68-4537-9225-c3c2cc1170b5.png)
> 
> 但我这边有一些额外的需求。
> 
> ## 背景
> 在我单独安装的 picgo-core 中，我通过 “picgo-plugin-web-uploader" 插件配置了自定义图床（不在默认提供的图床列表之内）。我的 `.picgo/config.json` 文件如下：
> 
> ```json
> {
>   "picBed": {
>     "current": "web-uploader",
>     "web-uploader": {
>       "customBody": null,
>       "customHeader": null,
>       "url": "XXXXXXXXXXXXXXXXXXXXXXX",
>       "paramName": "file",
>       "jsonPath": "data.o_url"
>     }
>   },
>   "picgoPlugins": {
>     "picgo-plugin-web-uploader": true
>   }
> }
> ```
> 
> 上述配置在命令行和 Typora 中都是验证正常可用的。
> 
> ## 问题
> 如果我在 vs-picgo 的配置中指定 picgo 的配置文件为 `/home/seven/.picgo/config.josn`, 也就是上面提到的自定义配置：
> ![image](https://user-images.githubusercontent.com/13358658/126909932-a8d48470-38d3-4640-9ef4-d4e30cc0bcd4.png)
> 控制台会提示 ”Can't find smms config", 导致无法上传图片。
> 
> ![image](https://user-images.githubusercontent.com/13358658/126909960-3d5a9cea-a1af-4429-8035-94f9dad7da1b.png)
> 
> ## 诉求
> 请问 vs-picgo 插件能否支持自定义图床呢？无需在 vs-code 中配置自定义图床，只需要能够使用我的 picgo-core 的配置文件即可。
> 
> 再次感谢！

这个诉求的核心是在于 `vs-picgo` 和 `picgo-core` 共用配置文件 🤔，我们先看下如果可行，会在后续版本支持哈

**Comment by seven-steven** [comment]
@Spades-S 或者说在不共用配置文件的情况下，我可以自己往 vs-picgo 安装并配置插件实现自定义图床吗？

**Comment by upupming** [comment]
@Seven-Steven 参考 #43 ，后续肯定会实现，不过暂时时间关系还没写😂，先把这个关了哈
