### ISSUE TITLE
上传方式错误：配置不起作用，直接默认了SMMS

### ISSUE THREAD

**Issue by JeffersonQin** [PicGo/vs-picgo#94]
### Describe the bug

我自己使用GitHub作为图床的，但是新版本更新之后，配置失效了（内容还都在，不过不起作用），上传图片直接走了SMMS，没办法更改方式。

### Screenshots

![image](https://user-images.githubusercontent.com/30655701/127094881-84cc8d9e-1502-4a10-83e5-d438166c828b.png)

### System information

- OS: Windows
- Version: Windows 10.0.19042

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
  Version: 1.57.1 (system setup)
  Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
  Date: 2021-06-17T13:28:07.755Z
  Electron: 12.0.7
  Chrome: 89.0.4389.128
  Node.js: 14.16.0
  V8: 8.9.255.25-electron.0
  OS: Windows_NT x64 10.0.19042
  ```

- `vs-picgo` version: 2.1.2

- Settings begin with `picgo`:

  ```json
  "picgo.picBed.current": "github",
  "picgo.picBed.github.branch": "master",
  "picgo.picBed.github.customUrl": "https://cdn.jsdelivr.net/gh/JeffersonQin/blog-asset@latest",
  "picgo.picBed.github.path": "usr/picgo/",
  "picgo.picBed.github.repo": "JeffersonQin/blog-asset",
  "picgo.customOutputFormat": "![](${url})",
  ```

**Comment by upupming** [comment]
@JeffersonQin 需要加一个：

```json
"picgo.picBed.uploader": "github",
```

参考：https://picgo.github.io/PicGo-Core-Doc/zh/guide/config.html#picbed-uploader

**Comment by JeffersonQin** [comment]
谢谢，问题解决了ヾ(≧▽≦*)o
