### ISSUE TITLE
可能是时候merge PicGo-Core的新feature了？

### ISSUE THREAD

**Issue by JeffersonQin** [PicGo/vs-picgo#96]
自从上次添加了WSL Clipboard的feature挺久没动静了（毕竟自己build不利于update，所以问问看是不是能够发布新release了🤣

**Comment by upupming** [comment]
@JeffersonQin 后续有更新的话肯定会带上这个feature的(只是改个版本号的问题），现在自己build有什么困难吗？

**Comment by JeffersonQin** [comment]
其实就是新release发布了的话我自己可能没法及时自动更新（其他都也没啥

**Comment by upupming** [comment]
OK，我更新一下吧😅

**Comment by JeffersonQin** [comment]
辛苦了，麻烦您了🤣

**Comment by upupming** [comment]
我已经在GitHub上传了release，可以麻烦你本地测试一下吗，没问题再发布到marketplace里面

ps: 因为我没有权限，可能得等明天早上找 @Spades-S 大佬发包了

**Comment by JeffersonQin** [comment]
好的好的 辛苦您了

**Comment by JeffersonQin** [comment]
我这边测试了一下 没问题
