### ISSUE TITLE
not working in ubuntu v20: command not found

### ISSUE THREAD

**Issue by bruceeewong** [PicGo/vs-picgo#98]
### Describe the bug

After installing vs-code extension: `PicGo`, all the commands in docs do not work.

Typed the following hotkeys, vscode pops up the same type of warning dialog:

```
ctl+alt+e: command 'picgo.uploadImageFromExplorer' not found
ctl+alt+u: command 'picgo.uploadImageFromClipboard' not found
ctl+alt+o: command 'picgo.uploadImageFromInputBox' not found
```

### To Reproduce

1. Download picgo in vscode, within ubuntu 20 system 
2. type in hotkey: `ctl+alt+e`
3. See vscode pop-up warning dialog with text: `command 'picgo.uploadImageFromExplorer' not found` 

### Expected behavior

should behave like doc descriptions, now does not work at all.

### Screenshots

![Screenshot from 2021-08-19 23-02-52](https://user-images.githubusercontent.com/17715132/130092650-06708ce5-b240-4a90-9b13-4e64c018b539.png)
![Screenshot from 2021-08-19 22-57-06](https://user-images.githubusercontent.com/17715132/130092649-31bab18f-cb3f-46f2-80b4-c6ae0e6fb461.png)

### System information

- OS: [e.g. Windows]
- Version [e.g. Windows 10]

### VSCode information

- `Help` -> `About` -> `Copy`

```txt
// Place you VScode `About` data here
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.0-27-generic
```

- `vs-picgo` version: `2.1.3`

- Settings begin with `picgo`: 

I haven't start to config it yet. 

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: No.

**Comment by upupming** [comment]
@bruceeewong Is there any logs in the console, please provide it.

**Comment by bruceeewong** [comment]
> @bruceeewong Is there any logs in the console, please provide it.

Seems no console at all.  

vscode says `command 'picgo.uploadImageFromExplorer' not found`, didn't go into picgo's function yet.

or where could I find any console in this situation?

**Comment by upupming** [comment]
@bruceeewong see the issue template for how to open the console
https://github.com/PicGo/vs-picgo/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md#additional-context
