### ISSUE TITLE
插件对于报错信息的不正确处理

### ISSUE THREAD

**Issue by JeffersonQin** [PicGo/vs-picgo#99]
- vs-picgo: 2.1.3
- VSCode Version: 1.57.1 (system setup)
- Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
- Date: 2021-06-17T13:28:07.755Z
- Electron: 12.0.7
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/30655701/130181812-eac904e4-3243-4982-ab5a-3f0b133215d2.png)

在失败的情况下还是显示上传成功.

（这是我在调试别的bug的时候发现的，其他bug会另行汇报）

**Comment by upupming** [comment]
这个是文件名有错误吗？这个属于是 picgo-core 的报错系统 handle 的有点问题，我周末看看。抱歉现在才回复，邮件进了垃圾箱

这个错误的重现方式是啥哈，可以提供一下吗

**Comment by JeffersonQin** [comment]
其实就是当剪切板文件路径获取有问题时就能重现。你可以在拿到文件路径后做一下判断，文件是否存在。

**Comment by upupming** [comment]
@JeffersonQin 不是很懂，怎么复现才能使出剪切板文件路径有问题
我知道了，我来修改一下吧

**Comment by JeffersonQin** [comment]
我前面看了一下代码，可能这个issue在Core里，不在这里。就是好像Core没有对脚本的报错做进一步处理

**Comment by JeffersonQin** [comment]
@upupming 谢谢，我大概了解了，我等会去Core在提一下（确实有点问题，因为script的脚本过于native，不是很好handle
